export const ROLES = {
  PLATFORM_SUPER_ADMIN: 'platform_super_admin',
  COMPANY_OWNER: 'company_owner',
  COMPANY_MANAGER: 'company_manager',
  TEAM_LEADER: 'team_leader',
  AGENT: 'agent',
  CUSTOMER: 'customer',
};


export const RESOURCES = {
  COMPANIES: 'companies',
  USERS: 'users',
  KNOWLEDGE_BASE: 'knowledge_base',
  CHAT: 'chat',
  TICKETS: 'tickets',
  EMBEDDINGS: 'embeddings',
  ANALYTICS: 'analytics',
  AUDIT_LOG: 'audit_log',
};

export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  MANAGE: 'manage',
};

export const CHANNELS = {
  WEB: 'web',
  TELEGRAM: 'telegram',
  WHATSAPP_MOCK: 'whatsapp_mock',
  MESSENGER_MOCK: 'messenger_mock',
};

export const TICKET_STATUS = {
  OPEN: 'open',
  IN_PROGRESS: 'in_progress',
  RESOLVED: 'resolved',
  CLOSED: 'closed',
};

export const TICKET_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
};

export const TICKET_CATEGORY = {
  BILLING: 'billing',
  NETWORK: 'network',
  PACKAGES: 'packages',
  COMPLAINT: 'complaint',
  PAYMENT: 'payment',
  REFUND: 'refund',
  OTHER: 'other',
};

export const CHAT_STATUS = {
  ACTIVE: 'active',
  CLOSED: 'closed',
};

export const KNOWLEDGE_TYPE = {
  PACKAGE: 'package',
  FAQ: 'faq',
  POLICY: 'policy',
  COMPLAINT_FLOW: 'complaint_flow',
};

export const EVENT_TYPES = {
  CHAT_MESSAGE: 'chat_message',
  CHAT_SESSION_CREATED: 'chat_session_created',
  TICKET_CREATED: 'ticket_created', 
  TICKET_UPDATED: 'ticket_updated',
  TICKET_RESOLVED: 'ticket_resolved',
  AI_ESCALATED: 'ai_escalated',
  AGENT_REPLIED: 'agent_replied',
  CHANNEL_INBOUND: 'channel_inbound',
  TICKET_CLAIMED: 'ticket_claimed',
  TICKET_CLOSED: 'ticket_closed',
};

export const RBAC_MATRIX = {
  [ROLES.PLATFORM_SUPER_ADMIN]: {
    [RESOURCES.COMPANIES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.KNOWLEDGE_BASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.CHAT]: [ACTIONS.READ, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.TICKETS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.EMBEDDINGS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.MANAGE],
    [RESOURCES.ANALYTICS]: [ACTIONS.READ, ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ, ACTIONS.MANAGE],
  },
  [ROLES.COMPANY_OWNER]: {
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.KNOWLEDGE_BASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.CHAT]: [ACTIONS.READ, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.TICKETS]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.MANAGE],
    [RESOURCES.EMBEDDINGS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.MANAGE],
    [RESOURCES.ANALYTICS]: [ACTIONS.READ, ACTIONS.MANAGE],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ, ACTIONS.MANAGE],
  },
  [ROLES.COMPANY_MANAGER]: {
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.KNOWLEDGE_BASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CHAT]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.TICKETS]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.MANAGE],
    [RESOURCES.EMBEDDINGS]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.ANALYTICS]: [ACTIONS.READ],
    [RESOURCES.AUDIT_LOG]: [ACTIONS.READ],
  },
  [ROLES.TEAM_LEADER]: {
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.KNOWLEDGE_BASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.CHAT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TICKETS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.EMBEDDINGS]: [ACTIONS.READ],
    [RESOURCES.ANALYTICS]: [ACTIONS.READ],
  },
  [ROLES.AGENT]: {
    [RESOURCES.KNOWLEDGE_BASE]: [ACTIONS.READ],
    [RESOURCES.CHAT]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TICKETS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.ANALYTICS]: [ACTIONS.READ],
  },
  [ROLES.CUSTOMER]: {
    [RESOURCES.CHAT]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.TICKETS]: [ACTIONS.READ],
  },
};
